# pgAdmin Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: elestio/pgadmin
          envFrom:
            - configMapRef:
                name: pgadmin-config
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          emptyDir: {}

---
# pgAdmin Service
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: pgadmin